// This file is generated by Slice Machine. Update with care!

import CallToAction from "./CallToAction"
import FooterLinks from "./FooterLinks"
import Hero from "./Hero"
import NavLinks from "./NavLinks"

export { CallToAction, FooterLinks, Hero, NavLinks }

export const components = {
  call_to_action: CallToAction,
  footer_links: FooterLinks,
  hero: Hero,
  nav_links: NavLinks,
}
